//! DBus proxies generated by `zbus`.
//!
//! Definitions follow the MPRIS v2.2 specification:
//! <https://specifications.freedesktop.org/mpris-spec/latest/>.
//!
//! Only the surface we actually need is declared; methods not used by the
//! application are left out to keep the binary small and avoid encouraging
//! unrelated DBus calls from elsewhere in the codebase.

use std::collections::HashMap;

use zbus::proxy;
use zbus::zvariant::OwnedValue;

/// Root MPRIS interface — identity, fullscreen, raise/quit.
#[proxy(interface = "org.mpris.MediaPlayer2", default_path = "/org/mpris/MediaPlayer2")]
pub trait MediaPlayer2 {
    #[zbus(property)]
    fn identity(&self) -> zbus::Result<String>;

    #[zbus(property)]
    fn desktop_entry(&self) -> zbus::Result<String>;

    fn quit(&self) -> zbus::Result<()>;
}

/// The `Player` sub-interface: actual playback control + metadata.
#[proxy(interface = "org.mpris.MediaPlayer2.Player", default_path = "/org/mpris/MediaPlayer2")]
pub trait Player {
    fn play_pause(&self) -> zbus::Result<()>;
    fn play(&self) -> zbus::Result<()>;
    fn pause(&self) -> zbus::Result<()>;
    fn next(&self) -> zbus::Result<()>;
    fn previous(&self) -> zbus::Result<()>;
    fn stop(&self) -> zbus::Result<()>;
    fn seek(&self, offset_usec: i64) -> zbus::Result<()>;

    // All readable Player properties are marked `emits_changed_signal =
    // "false"` to bypass zbus's property cache entirely. Two reasons:
    //
    // 1. `Position` is *spec-forbidden* from emitting PropertiesChanged, so the
    //    cache would otherwise be stuck at the first read.
    //
    // 2. For everything else, our PropertiesChanged subscriber races zbus's
    //    internal cache-updater for the same signal. Half the time we'd read
    //    `metadata()` *before* the cache had absorbed the new value, yielding
    //    the *old* track on the very signal that's telling us about the new
    //    one. Going uncached makes every read a fresh DBus call — cheap
    //    enough given we only refresh on signals + a 500 ms position tick.
    #[zbus(property(emits_changed_signal = "false"))]
    fn metadata(&self) -> zbus::Result<HashMap<String, OwnedValue>>;

    #[zbus(property(emits_changed_signal = "false"))]
    fn playback_status(&self) -> zbus::Result<String>;

    #[zbus(property(emits_changed_signal = "false"))]
    fn position(&self) -> zbus::Result<i64>;

    #[zbus(property(emits_changed_signal = "false"))]
    fn volume(&self) -> zbus::Result<f64>;

    #[zbus(property)]
    fn set_volume(&self, volume: f64) -> zbus::Result<()>;

    #[zbus(property)]
    fn can_play(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_pause(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_go_next(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_go_previous(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_seek(&self) -> zbus::Result<bool>;

    #[zbus(signal)]
    fn seeked(&self, position_usec: i64) -> zbus::Result<()>;
}
