//! DBus proxies generated by `zbus`.
//!
//! Definitions follow the MPRIS v2.2 specification:
//! <https://specifications.freedesktop.org/mpris-spec/latest/>.
//!
//! Only the surface we actually need is declared; methods not used by the
//! application are left out to keep the binary small and avoid encouraging
//! unrelated DBus calls from elsewhere in the codebase.

use std::collections::HashMap;

use zbus::proxy;
use zbus::zvariant::OwnedValue;

/// Root MPRIS interface — identity, fullscreen, raise/quit.
#[proxy(interface = "org.mpris.MediaPlayer2", default_path = "/org/mpris/MediaPlayer2")]
pub trait MediaPlayer2 {
    #[zbus(property)]
    fn identity(&self) -> zbus::Result<String>;

    #[zbus(property)]
    fn desktop_entry(&self) -> zbus::Result<String>;

    fn quit(&self) -> zbus::Result<()>;
}

/// The `Player` sub-interface: actual playback control + metadata.
#[proxy(interface = "org.mpris.MediaPlayer2.Player", default_path = "/org/mpris/MediaPlayer2")]
pub trait Player {
    fn play_pause(&self) -> zbus::Result<()>;
    fn play(&self) -> zbus::Result<()>;
    fn pause(&self) -> zbus::Result<()>;
    fn next(&self) -> zbus::Result<()>;
    fn previous(&self) -> zbus::Result<()>;
    fn stop(&self) -> zbus::Result<()>;
    fn seek(&self, offset_usec: i64) -> zbus::Result<()>;

    #[zbus(property)]
    fn metadata(&self) -> zbus::Result<HashMap<String, OwnedValue>>;

    #[zbus(property)]
    fn playback_status(&self) -> zbus::Result<String>;

    // The MPRIS spec explicitly says Position must NOT emit PropertiesChanged
    // (it changes continuously while playing). zbus caches `#[zbus(property)]`
    // values by default and only invalidates them on PropertiesChanged — which
    // means without this attribute the cached Position is stuck at "the value
    // we saw on the first read, forever". Marking it `emits_changed_signal =
    // "false"` tells zbus to always fetch fresh.
    #[zbus(property(emits_changed_signal = "false"))]
    fn position(&self) -> zbus::Result<i64>;

    #[zbus(property)]
    fn volume(&self) -> zbus::Result<f64>;

    #[zbus(property)]
    fn set_volume(&self, volume: f64) -> zbus::Result<()>;

    #[zbus(property)]
    fn can_play(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_pause(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_go_next(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_go_previous(&self) -> zbus::Result<bool>;

    #[zbus(property)]
    fn can_seek(&self) -> zbus::Result<bool>;

    #[zbus(signal)]
    fn seeked(&self, position_usec: i64) -> zbus::Result<()>;
}
